name: Deploy Deal Siren API

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: dealsirenapi
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        run: dotnet restore ./WeatherApi/WeatherApi.csproj

      - name: Build
        run: dotnet build ./WeatherApi/WeatherApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./WeatherApi/WeatherApi.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./publish
